- name: installing nginx
  hosts: web
  become: yes
  tasks: 
    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: starting nginx
      ansible.built.in.service:
        name: nginx
        state: started
        enabled: yes

    
  