- name: install nginx
  hosts: web
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: Starting nginx
      ansible.builtin.service:
      state: started
      enabled: yes