- name : to check the command and shell modules 
  hosts: localhost
  become : yes
  tasks: 
  - name : command module 
    ansible.builtin.command: echo "Hi Good mormning > /tmp/command.txt"
  - name : shell module  
    ansible.builtin.shell: echo "Hi Good mormning > /tmp/command.txt"
     