- name: To define variable
  hosts: localhost
  become: yes
  tasks:
  - name: print message
    ansible.builtin.debug:
      msg: "Hi This course is {{ Tool | default('Ansible') }}" 

- name: UPPER_CASE
  hosts: localhost
  become: yes
  vars:
   Greetings: Good Morning
  tasks:
  - name: convert into upper-case
    ansible.builtin.debug:
      msg: "Hi {{Greetings | upper}}"
