- name: To define variable
  hosts: localhost
  become: yes
  tasks:
  - name: print message
    ansible.builtin.debug:
      msg: "Hi This course is {{ Tool | default('Ansible') }}" 

- name: UPPER_CASE
  hosts: localhost
  become: yes
  vars:
   Greetings: Good Morning
  tasks:
  - name: convert into upper-case
    ansible.builtin.debug:
      msg: "Hi {{Greetings | upper}}"

- name: Lower-case
  hosts: localhost
  become: yes
  vars:
    Wishes: GOOD EVENING
  tasks: 
  - name: converting to lowercase
    ansible.builtin.debug:
      msg: "Hi {{Wishes | lower}}"

- name: remove duplicates
  hosts: localhost
  become: yes
  vars:
   numbers: [ 1,2,2,3,4,4,5,6 ]
  tasks:
  - name: removing duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: min & max
  hosts: localhost
  become: yes
  vars:
   age: [11,15,10,55]
  tasks:
  - name: printing min & maxi
    ansible.builtin.debug:
      msg: "min age is {{age | min }}, maximum age is {{age | max}}"
  
  - name: convert dictionary into list 
    hosts: localhost
    become: yes
    vars:
     dic-list:
        cource: Devops
        tools: Ansible
        Type: online
    tasks:
    - name: before converting dictionary to list
      ansible.builtin.debug:
        msg: "Before convrting {{dic-list}}"
    - name: after converting dictionary list
      ansible.builtin.debug:
        msg: "after converting {{dic-list | dict2items}}"
              
