- name: installing packages
  hosts: localhost
  become: yes

  task:
  - name: installing rpms
    ansible.built.in.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mqsql
    - postfix
    - nginx
    

