- name: installing packages
  hosts: localhost
  become: yes

  tasks:
  - name: installing rpms
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - postfix
    - nginx


