- name: To decleare the variables
  hosts: localhost
  become: yes
  vars:
    Place: "Bangalore"
    Date: "02"
    Month: "March"


  tasks:
    - name: to say a message
      ansible.builtin.debug:
        msg: "Hi Im Travelling to {{Place}} on {{Date}}nd {{Month}}."